### ISSUE TITLE
Set up docker if needed

### ISSUE THREAD

**Issue by varsityyy** [JoshuaRaybould/SSH#21]
Look into docker.

Will be useful for quick set up of our database we plan to include.

If agreed, setup must be done as soon as.

**Comment by JoshuaRaybould** [comment]
I'm looking into it now, it does seem like it will be useful so we can set up the database quickly and easily on our machines. I'll try and have it set up either today or end of tomorrow at the latest.

**Comment by JoshuaRaybould** [comment]
I'm pretty confident we'll use docker, so it would be a good idea for everyone to install it and the vscode extension for it when they get chance.

**Comment by JoshuaRaybould** [comment]
I have docker set up and am just waiting for the team to clarify the things about the database in my other issues, then I will create a pull request, when this goes through this issue can be closed. I do still want to see if there is a way to make gradle automatically run the docker compose file after this however (as for now you would have to run the necessary docker commands yourself before doing the build) but that is a separate issue.

**Comment by JoshuaRaybould** [comment]
On second thought I'll make a pull request just including the addition of docker, and set the tables up properly a bit later.
