### ISSUE TITLE
Hardcoded database data

### ISSUE THREAD

**Issue by JoshuaRaybould** [JoshuaRaybould/SSH#25]
As far as I can tell if someone were to populate the database it would only be populated for them (I don't think we can add it to github). This means we are probably going to need to put our hardcoded values in some kind of files so that we can fill up the database each time before use. Look into this please.

**Comment by ArmanAli05** [comment]
I've looked into it and apparently it's not very hard to just import tables from an excel into an SQL database, so we can just store all our tables on an excel file and import them as needed.

**Comment by JoshuaRaybould** [comment]
I think we have completed what was required for this part, so I'll close the issue.
