### ISSUE TITLE
New "recipes_items" database table

### ISSUE THREAD

**Issue by JoshuaRaybould** [JoshuaRaybould/SSH#30]
In our plan I don't think we go over how we are figuring out which items each recipe uses. I think it makes sense to introduce a recipes_items table that just stores recipe_id and item_id so we can handle the many to many relationship.

**Comment by varsityyy** [comment]
Yeah thats a good idea

**Comment by JoshuaRaybould** [comment]
I think in the example the database of recipes would be separate to our own (so the table wouldn't make sense) but for ours we are imagining its all in the SSH Cloud database anyway so I think it makes sense that we would have this table. I think @benjoseph05 or @ArmanAli05 should work on this once they've both completed their first unit of work.

**Comment by JoshuaRaybould** [comment]
I think this would also need to include some kind of "required_quantity" field so we know how much of an item a recipe needs. I think it makes sense for @benjoseph05 to handle this part, unless there is another way we're doing this?

**Comment by benjoseph05** [comment]
Wait so are we imagining that recipe items table is already in the SSH cloud? I'm confused on what the recipe items table would do?

**Comment by JoshuaRaybould** [comment]
Yeah, if we do this, I think we'd have to assume some table like this exists in the SSH Cloud. The purpose of it is to connect the recipe to each of the ingredients it needs, so we can tell what items the recipe needs and the quantity of the item it needs.
