### ISSUE TITLE
Setting up database

### ISSUE THREAD

**Issue by JoshuaRaybould** [JoshuaRaybould/SSH#38]
I have put the necessary database tables in the databaseSSH.sql file so these can automatically be loaded in when the postgres docker contain is ran. 

Next I plan to add a piece of test data to each of these and test that we can properly get data back, hopefully adding this to our CI.

**Comment by JoshuaRaybould** [comment]
Whilst the main portion of the database is set up and has been confirmed to work, after we further discussed it became apparent we may want to remove some tables, so I'll leave this issue open until we've fully decided and completed this part.

**Comment by JoshuaRaybould** [comment]
I think since we are planning to just hardcode recipes elsewhere we could do with removing the recipes table, I think there may be other stuff we want to clean up slightly so someone can do that as a bigger thing later on, in a dedicated branch, unless @benjoseph05 removes it when he is hardcoding the recipes in java. After this, this issue can be closed.

**Comment by benjoseph05** [comment]
With the JSON recipe file, we can remove the recipe csv file yes?

**Comment by JoshuaRaybould** [comment]
Your right yes, I have removed the csv and other no longer necessary database tables.

**Comment by JoshuaRaybould** [comment]
I think it's safe to say this part is done now.
