### ISSUE TITLE
Populating the entries in the recipe table

### ISSUE THREAD

**Issue by benjoseph05** [JoshuaRaybould/SSH#43]
When populating the recipe table, I plan on doing it on a csv file, which to my understanding is how Arman is doing it. Just wanted an update on the fields of the recipe table, is it the same as the EDR version or do we have any updates on fields?

**Comment by JoshuaRaybould** [comment]
Check the plan.md, I think it is pretty similar to EDR version. A csv file should work well with what I've done so far, so that's good.

**Comment by benjoseph05** [comment]
created a recipe csv file that should use the ingredients that is in arman's csv file
