### ISSUE TITLE
User Creation

### ISSUE THREAD

**Issue by ArmanAli05** [JoshuaRaybould/SSH#51]
Create the logic for adding users and their ingredients to be stored in the database

**Comment by ArmanAli05** [comment]
Hardcoding a test user to use as dummy data for other areas of the project while i work out the actual code for adding users and their ingredients to the database.

**Comment by JoshuaRaybould** [comment]
Good work, I've made use of the test user in part of my own section, and it has been quite helpful.

**Comment by ArmanAli05** [comment]
Created and implemented the User Creation to the App.java. Also added some test cases to allow us to pass the test coverage.
