### ISSUE TITLE
CI update

### ISSUE THREAD

**Issue by varsityyy** [JoshuaRaybould/SSH#59]
I realised that when CI runs, it is unclear what tests really fail when going into the build step. I'm thinking of modifying the java.yml file to handle separate tests to make it more clearer on what tests actually fail.

**Comment by varsityyy** [comment]
I'm having problems with running the separate tests.

- name: "Build project"
        run: ./gradlew app:compileJava

- name: "Database test"
        run: gradle test --tests org.example.DatabaseTest

      - name: "Quality test"
        run: gradle test --tests org.example.IngredientsTest
        
These are the commands I believe will work, if someone else could add them to the yml file that would be great.

**Comment by JoshuaRaybould** [comment]
Yeah, I'll check it out and try to do that now.

**Comment by JoshuaRaybould** [comment]
I've added these and they all seemed to work. I've added this to the CI and created a pull request.
