### ISSUE TITLE
Ranking Recipes Logic

### ISSUE THREAD

**Issue by varsityyy** [JoshuaRaybould/SSH#63]
I'm starting the logic to rank the recipes. I will be using @JoshuaRaybould functions MemoryIngredients() and StdoutIngredients() to get the user's ingredients list as well as there quality and quantity. I will then score recipes firstly on the user having all the items, then the quality as a secondary factor.

**Comment by JoshuaRaybould** [comment]
Memory ingredients and stdout ingredients are mainly for getting the ingredients as output to terminal or a test, you'll probably want to use the method in tenantsIngredints, I think there is a getIngredients method.

**Comment by varsityyy** [comment]
To be fair I only had a glance at you're code at the time, that function makes much more sense.

**Comment by JoshuaRaybould** [comment]
How is this going as of now?

**Comment by varsityyy** [comment]
I am about to do a pull request, the test file is not 100% correct so if someone could take a look. I have finished the main logic however.

**Comment by JoshuaRaybould** [comment]
Sounds good, I'll look at that right away.
