### ISSUE TITLE
Any updates on the recipes

### ISSUE THREAD

**Issue by JoshuaRaybould** [JoshuaRaybould/SSH#67]
How is the hardcoding of the recipes and the function to return recipes that have items in a list of provided items going @benjoseph05, any updates.

**Comment by benjoseph05** [comment]
currently working on returning recipes based on the ingredients the user has

**Comment by benjoseph05** [comment]
when returning the recipes, are we only returning the recipe instructions and recipe name or all of it? Additionally just to get it right the function looks at the available ingredients the user has, and checks if it is in any of the recipes ingredients that is in the load recipes file and if so returns those recipes?

**Comment by JoshuaRaybould** [comment]
I think you'll return everything to do with the recipe, since we probably want to show it all to the user but also @varsityyy will need the required quantities of ingredients so that he can then rank the recipes based on the user's ingredients. And yeah, I think what you are saying it is correct, so long as an ingredient that the user has appears in a recipe that recipe should be returned. 

I think in reality if we were using a separate database or API we'd have to grab recipes based on a single item at a time (which could lead to duplicates which we'd then remove). We could make the function work more like that and then remove any duplicates if you think that makes sense, but I think the original idea probably makes enough sense to simulate what we want.

**Comment by JoshuaRaybould** [comment]
I don't think it matters too much where it is coded (at least not for now) so long as it works.

**Comment by JoshuaRaybould** [comment]
I've thought a bit more and do also think having it hardcoded in java may be slightly too simple (maybe we could have it in a json file and try to have the function simulate the actual system more closely like I suggested before) but for now this will be fine so we can make sure other key elements of our design are working.

**Comment by JoshuaRaybould** [comment]
It probably also makes sense to put this stuff in a different folder to make it clear that it is a separate system (since this is simulating the data we get from the provided recipe database)

**Comment by benjoseph05** [comment]
I tried pushing my branch onto the main so I did git rebase main but when I did it returned a conflict with the main branch and my branch of LoadRecipes.java and said to resolve the conflict. Don't quite understand what to do so for now I did git rebase --abort. Should I ignore the conflict?

**Comment by JoshuaRaybould** [comment]
You can probably ignore the conflict, but if you open vscode after being told about them you should be given an option to decide what to keep (between your changes and whatever is conflicting)

**Comment by benjoseph05** [comment]
my method uses the getIngredients() method in the TenantIngredient class but it doesn't seem to be retrieving the users ingredients - would I need to do something with docker on terminal?

**Comment by JoshuaRaybould** [comment]
You would need to run Docker yes, but you don't need to use this function as @varsityyy will use it and then provide your function the list of ingredients. 
If you are trying to test it though you can run Docker with: docker compose -f docker-compose.yml up -d

**Comment by benjoseph05** [comment]
I see because right now what my function does is takes in a tenant id and then creates a new tenantingredient object and thats how it calls the getIngredients.
Would I need to run the docker in the terminal before I run the test?

**Comment by JoshuaRaybould** [comment]
Yes run docker because it sets up the database and loads certain data like the test user.

**Comment by benjoseph05** [comment]
I think because my builds still seem to fail from before can i push the changes and see if the test cases work for you?

**Comment by JoshuaRaybould** [comment]
If you think it should all work you could push it then create a pull request so you can see where it fails in our continuous integration, but yeah at least push the changes and I'll see if there is a way I can check it out on my machine (unless you do a pull request and it passes).

**Comment by benjoseph05** [comment]
does this mean that it has failed the continuous integration?

$ git push origin feature/loadrecipes
To https://github.com/JoshuaRaybould/SSH.git
 ! [rejected]        feature/loadrecipes -> feature/loadrecipes (non-fast-forward)
error: failed to push some refs to 'https://github.com/JoshuaRaybould/SSH.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by JoshuaRaybould** [comment]
No, I think this is some other problem with your branch not being up to date. I'm not 100% sure on how to resolve this, I would just go through the steps to make sure it is up to date, at worst if you are sure that what you have on your device is what you want to put on GitHub I think you can force push somehow (you'd have to look this up I don't remember the exact command)

**Comment by JoshuaRaybould** [comment]
You have created a draft pull request though that I can see and that has passed the continuous integration.

**Comment by JoshuaRaybould** [comment]
Actually if the issue is to do with conflicts with the main branch stuff I think you are going to have to find a way to resolve it (I don't think force pushing is an option)

**Comment by JoshuaRaybould** [comment]
@benjoseph05 any progress?

**Comment by benjoseph05** [comment]
draft pull request*

**Comment by benjoseph05** [comment]
I've created a new branch called recipeMatch which has the functionality and send a pull request.  If you can check that the function works properly for you and let me know if it passes then that would be great

**Comment by JoshuaRaybould** [comment]
It has passed continuous integration so I'm assuming it works. You've kept good code coverage too so that's good, but I've left some comments on it, and you need to make it take a list of ingredients rather than a user id because that is what @varsityyys function will provide you.

**Comment by benjoseph05** [comment]
Can someone approve my pull request for the recipe matching and json recipe file?
