### ISSUE TITLE
Looking into Mockito

### ISSUE THREAD

**Issue by varsityyy** [JoshuaRaybould/SSH#69]
We need to explore how Mockito can be effectively integrated into our project to improve the quality of unit tests. Specifically, it will help us isolate dependencies and test critical logic like the rankRecipes method in the RecipeRanking class without relying on real database or external dependencies.

**Comment by varsityyy** [comment]
Mockito is pretty much allows us to simulate the behavior of external dependencies like databases or APIs, enabling us to focus on testing the logic of specific methods. This can improve the reliability and maintainability of our unit tests.

**Comment by JoshuaRaybould** [comment]
Alright that sounds good, I still need to look at improving the tests for my unit (where I get a tenant's ingredients) so hopefully I can make use of it there.

**Comment by JoshuaRaybould** [comment]
From what I've briefly seen this sounds good but looks somewhat difficult, have you made any progress with it @varsityyy.

**Comment by varsityyy** [comment]
Still having problems with it. Its not recognising it even when i build it. Still trying to figure it out.

**Comment by varsityyy** [comment]
Decided to not use Mockito since i couldn't get it to work.
