### ISSUE TITLE
Displaying Recipe Matching

### ISSUE THREAD

**Issue by ArmanAli05** [JoshuaRaybould/SSH#85]
Me and Josh have been looking over the code and have realised that the recipes dont display in order of proportion of ingredients matched? I don't know if we've misread the logic or it hasn't been implemented.

**Comment by benjoseph05** [comment]
Can you explain more about that?

**Comment by varsityyy** [comment]
I'm looking into it now, yes I do not have any logic for actually ranking the recipes in that specified order, I just have the thresholds. Something i completely missed.

**Comment by varsityyy** [comment]
I have managed to sort this out now.
