### ISSUE TITLE
random date captured leads to incorrect quality scores.

### ISSUE THREAD

**Issue by JoshuaRaybould** [JoshuaRaybould/SSH#89]
It looks like the random date captured can be either before or after the current date, where in reality we can only have captured it on or before the current date. This is leading to some quality scores greater than 1, also currently it seems the current date time stamp is being put in the database rather than the calculated one. I'm looking over this now and believe I can solve these issues, would you like me to go ahead with this @ArmanAli05 or would you prefer do this yourself?

**Comment by JoshuaRaybould** [comment]
I've been working on this and plan to make a pull request soon if someone could look over it, preferably @ArmanAli05 as he will be able to tell if I've done something wrong more easily, but anyone will do.

**Comment by ArmanAli05** [comment]
Yep, i remember mentally noting that down as before i did a weird way instead of doing captured date as todays date and did it so it was a week before todays date. But then forgot to revert it upon editing the code. Thanks for fixing it!
